name: url-shortener

services:
  valkey:
    image: valkey/valkey:7.2.5-alpine3.19
    command: valkey-server /etc/valkey/valkey.conf
    volumes: 
      - ./valkey.conf:/etc/valkey/valkey.conf
    ports:
      - '6379:6379'

volumes:
  valkey:
    driver: local