version: '3.8'

services:
  redis:
    image: redis:7.0.11-alpine
    command: redis-server /etc/redis/redis.conf
    volumes: 
      - ./redis.conf:/etc/redis/redis.conf
    ports:
      - '6379:6379'

volumes:
  redis:
    driver: local